@startuml

title calibration sequence

start

:both LEDs on;

:for calibration keep button pressed;

if (button pressed?) then (yes)
  'passive acceleromenter calibration'
  :red LED on;

  :do not move the sensors:
  each sensor calibrates
  accelerometer in current
  position;

  :accelerometer calibration
   data is being saved;

  'active magnetometer calibration'
  :yellow LED on;

  :active magnetometer calibration starts;
  
  :rotate sensor 1 in x, y, z direction;
  
  :yellow LED off;
  
  :rotate sensor 2 in x, y, z direction;
  
  :yellow LED on;
  
  :rotate sensor 3 in x, y, z direction;
  
  :yellow LED off;
  
  :rotate sensor 4 in x, y, z direction;
  
  :and so on...;

  :magnetometer calibration
   data is being saved;

else (no)
  :both LEDs off;

  :load accelerometer and magnetometer
   calibration data for each sensor
   from memory;

  if (load successful) then (yes)
    :configure sensor
     with loaded data;
  else (no)
    :skip configuration;
  endif

endif

:two LEDs are blinking
 for 2 seconds;

:both LEDs on;

:if stage north should be set
point gyro on hardware input 2 (left_upper_arm) direction FOH;

:do not move sensors for 10 seconds 
and hold button pressed to apply new north;

:both LEDs off;

if (button pressed?) then (yes)
  :save new north
   data to memory;
else (no)

endif

:load north angle from memory;

:set north for each sensor;

:blink LEDs 20x;

stop

@enduml
